# Generated by Django 3.1.6 on 2021-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0008_paperlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordposition',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='wordposition',
            name='position',
        ),
        migrations.AddField(
            model_name='wordposition',
            name='frequency',
            field=models.IntegerField(default=0, verbose_name='frequency'),
        ),
        migrations.AddField(
            model_name='wordposition',
            name='tf_idf',
            field=models.TextField(default='', verbose_name='tf_idf'),
            preserve_default=False,
        ),
    ]
